### ISSUE TITLE
Building the "smallest sample" fails

### ISSUE THREAD

**Issue by gldraphael** [picrap/FIGlet#4]
I have the following code:

```cs
using FIGlet;
using FIGlet.Utility;

var helloWorld = FIGdriver.DefaultFont.Render("Hello, world");
Console.WriteLine(helloWorld);
```

With the package imported as the following in csproj:

```xml
<PackageReference Include="FIGlet-_-lib" Version="1.0.8" />
```

It fails with:

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at FIGlet.FIGdriver.get_DefaultFont()
   at Program.<Main>$(String[] args) in C:\Users\galdin\projects\figlet-exp\Program.cs:line 4
```

**Comment by picrap** [comment]
Thank you, this is fixed now (version 1.0.9 should be available in the next minutes)
